### ISSUE TITLE
it just wont work

### ISSUE THREAD

**Issue by KadenPrice406** [HarshalKudale/NoMoreEdge#17]
i already have edge deleted from my system but when i try to use a search query it trys to open edge before failing and not doing it at all

**Comment by KadenPrice406** [comment]
here's a video if that helps

https://user-images.githubusercontent.com/80788875/149609257-c25d653f-6322-455a-b2d6-7952fda8157d.mp4

o

**Comment by HarshalKudale** [comment]
Software requires edge to be installed. They is not way to intercept those URLs without  having edge installed. Other options are either blocked by Microsoft or they need to kept running in background. 

You can install Edge and then NoMorEdge with nuke edge installed so that edge wont work anymore but software will.

**Comment by KadenPrice406** [comment]
Thank you, that worked. Sucks that I have to have edge on my system but I love the nuke edge option. great work
